### ISSUE TITLE
How to install touchcursor-linux

### ISSUE THREAD

**Issue by AlienKevin** [donniebreve/touchcursor-linux#11]
Hi, I just switched from windows 10 to ubuntu 18.04 LTS. Could you please tell me where to clone the git repo and how the rest of "make" and "make install" work? I cloned touchcursor in `home` folder and run "make" and "make install" just fine but the program is not working. I then move the whole touchcursor folder to `/usr/local`. What should I do? Thanks a lot.

**Comment by donniebreve** [comment]
I am not sure if Ubuntu uses systemd, which is what I use to make this application run as a service. You should be able to clone the repo, then run `make` and `make install` to get the application in your command list (not sure if that is the right term). The program won't run at start up, but you can open a terminal and run `touchcursor`.

**Comment by AlienKevin** [comment]
I tried `touchcursor` but it's not working, here's the message:
found device name in config
error: please specify the keyboard device name in the configuration file

**Comment by donniebreve** [comment]
Make sure you update /etc/touchcursor/touchcursor.conf: https://github.com/donniebreve/touchcursor-linux/blob/master/touchcursor.conf

**Comment by AlienKevin** [comment]
Thank you so much. Touchcursor is working like a charm! Do you know a way to autoload touchcursor on startup? And is there a way to enable touchcursor for both my Bluetooth keyboard and laptop keyboard?

**Comment by donniebreve** [comment]
You have to make sure you are using systemd for it to start automatically. The ‘make install’ command does all the necessary work to install as a service with systemd. If you can find an error message I may be able to help more.

Right now the app only captures one keyboard at a time, but I may look into adding that feature.

**Comment by AlienKevin** [comment]
Thanks for your help. Touchcursor-linux really saved my day because my brain is so used to those shortcuts from touchcursor in Windows.
