### ISSUE TITLE
Using Capslock as hyper

### ISSUE THREAD

**Issue by baggsie** [donniebreve/touchcursor-linux#16]
Firstly thanks for a great application - it was the one thing I really miss from Windows.

Ideally I would like to use Capslock in place of the space for the hyper key but am having no luck changing touchcursor.conf

I've tried with no luck: 
`
HYPER1=KEY_CAPSLOCK
HYPER1=KEY_CAPS
HYPER1=KEY_CAPSL
`
Do you know if this functionality is possible and if maybe I'm missing something please?

Thanks,

Operating System: Manjaro Linux 
KDE Plasma Version: 5.16.5
KDE Frameworks Version: 5.62.0
Qt Version: 5.13.1
Kernel Version: 5.2.11-1-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i5-6300U CPU @ 2.40GHz
Memory: 11,1 GiB of RAM

**Comment by itgoyo** [comment]
@baggsie if you want to make Capslock as hyper,you must comment this line of code

touchcursor-linux/keys.c

```
// case KEY_CAPSLOCK
```
and rebuild the project,it works for me.

**Comment by donniebreve** [comment]
@baggsie @itgoyo are you familiar with git? If so, can you pull the allow-modifier-keys branch, rebuild, and do some testing? I did a quick test with capslock and it seems to work fine. If you are not sure how to do what I am asking, let me know and I will simple merge the PR.

**Comment by itgoyo** [comment]
@donniebreve Sorry, I understand what you mean wrong, and push the extra pr，I had try the code what you push on allow-modifier-keys branch and it work fine to me

**Comment by donniebreve** [comment]
@baggsie please close this issue when you have a chance to confirm the fix. Thanks!

**Comment by baggsie** [comment]
Works perfectly -  thanks for your work @itgoyo & @donniebreve
