### ISSUE TITLE
Pressing a modifier key after spacebar, touchcursor mode gets disabled and sends a Space

### ISSUE THREAD

**Issue by NeKJ** [donniebreve/touchcursor-linux#19]
After the pull request merging: https://github.com/donniebreve/touchcursor-linux/pull/17 the following nasty bug has being introduced:

**steps to reproduce**

1. press Spacebar
2. press Left Shift key

**expected results**
Nothing changes. no keys are sent and touchcursor remains in "touchcusor mode" (for lack of a better word).

**actual results**
_SPACE_ key event is sent and "touchcursor mode" gets disabled, resulting in repeating spaces while spacebar is still holded down.

This causes several issues whenever a modifier key is pressed e.g. hitting a hotkey like ctrl+left arrow to go back one word, or pressing shift to capitalize a character etc) and instead it outputs spaces in all kinds of situations breaking all kinds of cases causing typing havoc. For some of us, who are heavily using hotkeys/shortcuts, means that it happens almost all of the time, therefore making touchcursor  practically unusable.

Reverting back to bcfd3fb72203daeeec3cc8d46488ac4ea5044759, fixes this and works like a charm!

**Comment by donniebreve** [comment]
Modifier keys, when output, do not block the repeating of the hyper key like other "regular" keys do. I added something to output the modifier key as is. Cleaned up the testing code too. Seems to retain functionality for mapping modifier keys as hyper.

Please close this issue after you confirm. Thanks!

**Comment by donniebreve** [comment]
Closing for @NeKJ.
