### ISSUE TITLE
Have touchcursor running for multiple keyboards simultaneously

### ISSUE THREAD

**Issue by mattiasJohnson** [donniebreve/touchcursor-linux#46]
I'm using a bluetooth keyboard sometimes and it would be nice if I could have touchcursor working for both my laptop keyboard and the bluetooth keyboard at the same time. As of now I've got a script that changes the config and restarts the service for each time I switch but a native option in the config to give two keyboard names would be even better! Is this something that you think would make sense implementing? Also thanks for the amazing program.

**Comment by Adda0** [comment]
Hello, absolutely. I myself have the same problem.

I plan to work on improving TouchCursor in the summer, when I will have some spare time. As of now, I am unfortunately occupied with other stuff. When I manage to get back to TouchCursor, multi-keyboard support is one of the issues I want to address, along with better logging and support for multiple hyper keys with separate key bindings.

I am glad you enjoy TouchCursor. Wish you all the best.

**Comment by donniebreve** [comment]
See #12

**Comment by Adda0** [comment]
Hey, @donniebreve. Correct me if I am wrong, but I think that what is required here is for TouchCursor to work **simultaneously** for two or more keyboards connected to the computer **at the same time**. Yeah, the changes to the config are redundant if you want TouchCursor to work only for one keyboard at the time (and the other keyboard has to be removed or lower in the list in the config). But if you have both keyboards simultaneously connected and want to switch between them, there is no other option than to change the config each time and restart the service. But even then, you cannot have TouchCursor working for both of them at the same time.
