### ISSUE TITLE
Issue in multi-keyboard capture

### ISSUE THREAD

**Issue by 1999shaswat** [donniebreve/touchcursor-linux#61]
### Issue:
If it fails to find the "last device" in the list, it won't connect to any device. Ideally, it should connect to "last successfully found device" in the list. 

### Logs
```
info: reloading
info: searching for device Name="AT Translated Set 2 keyboard":1
info: found the device event path: /dev/input/event3
info: searching for device Name="Keychron Keychron K2":1
error: could not find the event path for device: Name="Keychron Keychron K2":1
info: searching for device Name="Keychron K2":1
error: could not find the event path for device: Name="Keychron K2":1
error: no input device was configured (or the event path was not found).
error: could not capture the keyboard device
info: you may update the configuration file to have the application attempt discovering the input device again.
info: reloading
info: searching for device Name="AT Translated Set 2 keyboard":1
info: found the device event path: /dev/input/event3
info: searching for device Name="Keychron Keychron K2":1
error: could not find the event path for device: Name="Keychron Keychron K2":1
info: searching for device Name="Keychron K2":1
info: found the device event path: /dev/input/event13
info: attempting to cature: '/dev/input/event13'
info: successfully captured input device: Keychron K2 (/dev/input/event13)
```
### Info:
AT Translated Set 2 keyboard = Internal Laptop keyboard
Keychron Keychron K2 = External usb keyboard 
Keychron K2 = External bluetooth keyboard 

### Observations:
1. After reordering config file to this:
```
[Device]
Name="AT Translated Set 2 keyboard"
Name="Keychron Keychron K2"
Name="Keychron K2"
```
Touchcursor is taking "Keychron K2" as input and my External bluetooth keyboard is working.

2. When only Internal laptop keyboard is present and other keyboards are disconnected, touchcursor is not taking it as input device. (can be seen in logs too)

**Comment by donniebreve** [comment]
Please post some output logs: https://github.com/donniebreve/touchcursor-linux/wiki/Troubleshooting

**Comment by 1999shaswat** [comment]
### Logs
```
info: reloading
info: searching for device Name="AT Translated Set 2 keyboard":1
info: found the device event path: /dev/input/event3
info: searching for device Name="Keychron Keychron K2":1
error: could not find the event path for device: Name="Keychron Keychron K2":1
info: searching for device Name="Keychron K2":1
error: could not find the event path for device: Name="Keychron K2":1
error: no input device was configured (or the event path was not found).
error: could not capture the keyboard device
info: you may update the configuration file to have the application attempt discovering the input device again.
info: reloading
info: searching for device Name="AT Translated Set 2 keyboard":1
info: found the device event path: /dev/input/event3
info: searching for device Name="Keychron Keychron K2":1
error: could not find the event path for device: Name="Keychron Keychron K2":1
info: searching for device Name="Keychron K2":1
info: found the device event path: /dev/input/event13
info: attempting to cature: '/dev/input/event13'
info: successfully captured input device: Keychron K2 (/dev/input/event13)
```
### Info:
AT Translated Set 2 keyboard = Internal Laptop keyboard
Keychron Keychron K2 = External usb keyboard 
Keychron K2 = External bluetooth keyboard 

### Observations:
1. After reordering config file to this:
```
[Device]
Name="AT Translated Set 2 keyboard"
Name="Keychron Keychron K2"
Name="Keychron K2"
```
Touchcursor is taking "Keychron K2" as input and my External bluetooth keyboard is working.

2. When only Internal laptop keyboard is present and other keyboards are disconnected, touchcursor is not taking it as input device. (can be seen in logs too)

**Comment by 1999shaswat** [comment]
Hi, I have updated the issue description with logs. Can you please take a look?

**Comment by 1999shaswat** [comment]
Hi, @donniebreve I have updated the issue description with logs. Can you please take a look?

**Comment by donniebreve** [comment]
Hello @1999shaswat, this should be fixed in https://github.com/donniebreve/touchcursor-linux/commit/b8b647106899dc6e691b57a9973d636bb83dae07. Please try it out.

**Comment by 1999shaswat** [comment]
Issue is fixed. Thanks a lot.
