### ISSUE TITLE
how to use together with keyd

### ISSUE THREAD

**Issue by CRAG666** [donniebreve/touchcursor-linux#66]
This project looks amazing, but currently I have keyd installed and I have mapped many keys I would like to be able to use it together with keyd, do you think it works?

**Comment by donniebreve** [comment]
I believe both projects are using the same device capture method, so I don't think both will work at the same time. It looks like `keyd` is more featured than this project. What's your reason for trying to use both projects at the same time?

**Comment by auouymous** [comment]
From a quick glance, keyd appears to only support modifier keys to access its layers. Would it not be possible to have touchcursor or keyd read from the virtual device the other creates?

**Comment by auouymous** [comment]
I tried to switch to keyd a while back and it was working fine with touchcursor running. I had touchcursor on spacebar and was testing keyd on an overloaded apostrophe.

@CRAG666 Are you still wanting to use both?
