### ISSUE TITLE
how to make it active?

### ISSUE THREAD

**Issue by qq963598371** [donniebreve/touchcursor-linux#72]
I have done every step in order. But I do not know how to make it active backarond. It is very different from win.

**Comment by donniebreve** [comment]
We need more information. See https://github.com/donniebreve/touchcursor-linux?tab=readme-ov-file#how-to-install.

**Comment by qq963598371** [comment]
![image](https://github.com/donniebreve/touchcursor-linux/assets/35451263/494be99a-5260-4b4d-96f0-5c0853a59a6b)
the command window is up. Maybe it is ok. But long pressing spacekey is still space function~

**Comment by donniebreve** [comment]
Make sure you have edited the config file appropriately.

**Comment by qq963598371** [comment]
so how to open the file of " Modify the config file (~/.config/touchcursor/touchcursor.conf) to your liking"

**Comment by donniebreve** [comment]
Open that file with the editor of your choice.

**Comment by qq963598371** [comment]
I found nothing need to modify. After Step5 key with Space is still no effect.
![image](https://github.com/donniebreve/touchcursor-linux/assets/35451263/309f74b8-bcc5-4ed7-b0fe-b5a803794d5e)
![image](https://github.com/donniebreve/touchcursor-linux/assets/35451263/691fb419-65ea-4278-8703-a265ba7f292e)

**Comment by donniebreve** [comment]
1. You did not edit the file I referenced. You are editing the file in the repo you downloaded not the one in your home directory (`~`).
2. You've somehow deleted the top part of the config file that configures your keyboard name, which is seemingly the part you are missing to make this work.

**Comment by qq963598371** [comment]
I have copied the config file contexts to the file vim ~/.config/~ as step4. But when I saved the file . It came with "e212 can't open file for writing"
